apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmx-demo
  labels:
    app: htmx-demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: htmx-demo
  template:
    metadata:
      labels:
        app: htmx-demo
    spec:
      terminationGracePeriodSeconds: 5  # Ensure old pods terminate quickly
      containers:
        - name: htmx-demo
          image: REGISTRY_PLACEHOLDER/htmx-demo:VERSION_PLACEHOLDER  # Dynamically replaced by Jenkins
          imagePullPolicy: Always  # Ensures the latest version is always pulled
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2  # Reduce delay for faster pod availability
            periodSeconds: 5  # Check readiness more frequently
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: do-registry-secret  # Ensure this secret exists
---
apiVersion: v1
kind: Service
metadata:
  name: htmx-demo-service
spec:
  selector:
    app: htmx-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Change to ClusterIP if using an Ingress
