apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmx-demo
  labels:
    app: htmx-demo
spec:
  replicas: 3  # Adjust based on your scaling needs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: htmx-demo
  template:
    metadata:
      labels:
        app: htmx-demo
    spec:
      containers:
        - name: htmx-demo
          image: registry.digitalocean.com/your-docr-repo/htmx-demo:latest  # Update with your DOCR image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: do-registry-secret  # Ensure this secret exists
---
apiVersion: v1
kind: Service
metadata:
  name: htmx-demo-service
spec:
  selector:
    app: htmx-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Change to ClusterIP if using an Ingress
