apiVersion: v1
kind: Secret
metadata:
  name: do-registry-secret
  namespace: default
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <PASTE_YOUR_BASE64_ENCODED_STRING_HERE>